articles/urls.py
from django.urls import path
from . import views
from comments import views as comment_views

app_name = "articles"

urlpatterns = [
    path("new/", views.new, name="new"),
    path("<int:id>/edit", views.edit, name="edit"),
    path("<int:id>/comments", comment_views.create, name="create_comment"),
    path("<int:id>/like", views.like, name="like"),
    path("<int:id>", views.detail, name="detail"),
    path("", views.index, name="index"),
]

pages/urls.py
from django.urls import path
from . import views
from articles.views import index

app_name = "pages"

urlpatterns = [
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("pricing/", views.pricing, name="pricing"),
    path("", index, name="home"),
    path("test/", views.test, name="test"),
]

wretch/urls.py
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("", include("pages.urls")),
    path("articles/", include("articles.urls")),
    path("comments/", include("comments.urls")),
    path("users/", include("users.urls")),
    path("sessions/", include("sessions.urls")),
    path("payments/", include("payments.urls")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls()

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=200, null=False)
    content = models.TextField(null=True)
    is_published = models.BooleanField(default=False, null=False)
    user = models.ForeignKey(
        User,
        default=None,
        null=True,
        on_delete=models.SET_NULL,
    )
    likers = models.ManyToManyField(
        User,
        related_name="liked_articles",
        through="FavoriteArticle",
    )

    def __str__(self):
        return self.title


class FavoriteArticle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

articles/forms.py
from django.forms import ModelForm, TextInput, Textarea, CheckboxInput
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "is_published"]
        labels = {
            "title": "標題",
            "content": "內文",
            "is_published": "是否發布",
        }
        widgets = {
            "title": TextInput(attrs={"class": "input"}),
            "content": Textarea(
                attrs={
                    "class": "textarea",
                    "rows": 5,
                }
            ),
            "is_published": CheckboxInput(attrs={"class": "checkbox"}),
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from comments.forms import CommentForm
from .models import Article
from .forms import ArticleForm


def index(request):
    if request.method == "POST" and request.user.is_authenticated:
        form = ArticleForm(request.POST)
        article = form.save(commit=False)
        article.user = request.user
        article.save()

        messages.success(request, "新增成功")
        return redirect("articles:index")
    else:
        articles = Article.objects.order_by("-id")
        return render(request, "articles/index.html", {"articles": articles})


@login_required
def new(request):
    form = ArticleForm()
    return render(request, "articles/new.html", {"form": form})


def detail(request, id):
    if request.POST and request.user.is_authenticated:
        article = get_object_or_404(Article, pk=id, user=request.user)

        if request.POST["_method"] == "patch":
            form = ArticleForm(request.POST, instance=article)
            form.save()

            messages.success(request, "更新成功")
            return redirect("articles:detail", article.id)

        if request.POST["_method"] == "delete":
            article.delete()

            messages.warning(request, "刪除成功")
            return redirect("articles:index")
    else:
        article = get_object_or_404(Article, pk=id)
        comment_form = CommentForm()
        comments = (
            article.comment_set.select_related("user")
            .filter(deleted_at=None)
            .order_by("-id")
        )

        return render(
            request,
            "articles/detail.html",
            {
                "article": article,
                "comment_form": comment_form,
                "comments": comments,
                "liked": article.likers.contains(request.user),
            },
        )


@login_required
def edit(request, id):
    article = get_object_or_404(Article, pk=id, user=request.user)
    form = ArticleForm(instance=article)
    return render(
        request,
        "articles/edit.html",
        {"article": article, "form": form},
    )


@require_POST
@login_required
def like(request, id):
    article = get_object_or_404(Article, pk=id)
    liked = False

    if article.likers.contains(request.user):
        article.likers.remove(request.user)
    else:
        article.likers.add(request.user)
        liked = True

    return render(
        request,
        "ui/like_button.html",
        {
            "article": article,
            "liked": liked,
        },
    )

articles/templates/articles/detail.html
{% extends "layouts/default.html" %}

{% block content %}

現在時刻：{% now "jS F Y H:i:s" %}

<div class="flex gap-2 items-center">
  <a href="{% url 'articles:edit' article.id %}" class="btn btn-xs btn-success">編輯</a>
  <form action="{% url 'articles:detail' article.id %}" method="post">
    <input type="hidden" name="_method" value="delete" />
    {% csrf_token %}
    <button class="btn btn-xs btn-error">刪除</form>
  </form>
</div>

{% include "ui/like_button.html" with article=article liked=liked only %}

<h1 class="text-3xl">Hello, {{ article.title }}</h1>
<article>
  {{ article.content|linebreaks }}
</article>
<hr />
<h3>留言區</h3>

<form hx-post="{% url 'articles:create_comment' article.id %}"
      hx-target="#comment-section"
      hx-swap="afterbegin"
      hx-on::after-request="if(event.detail.successful) this.reset()"
      x-data
      >
  <div class="flex flex-col">
    {{ comment_form.content.label_tag }}
    {{ comment_form.content }}
  </div>
  <button :disabled="{{ user.is_authenticated|yesno:"false,true" }}" class="btn btn-primary btn-sm">新增</button>

</form>

<ul id="comment-section">
  {% for comment in comments %}
    {% include "comments/comment.html" with comment=comment user=user only %}
  {% endfor %}
</ul>

{% endblock %}

articles/templates/articles/edit.html
{% extends "layouts/default.html" %}

{% block content %}
<h1 class="text-3xl">編輯文章：{{ article.title }}</h1>

<form action="{% url 'articles:detail' article.id %}"
      method="post"
      class="flex flex-col gap-4">
      <input type="hidden" name="_method" value="patch" />

  {% csrf_token %}

  {% for field in form %}
    <div class="flex flex-col">
      {{ field.label_tag }}
      {{ field }}
    </div>
  {% endfor %}

  <div>
    <button class="btn btn-success">更新文章</button>
  </div>
</form>

{% endblock %}

articles/templates/articles/index.html
{% extends "layouts/default.html" %}

{% block content %}

<h1 class="text-3xl">文章列表</h1>
<a class="btn btn-success" href="{% url 'articles:new' %}">新增文章</a>
<hr />

{% for article in articles %}
<article class="mb-8">
  <h2>
    {% if article.is_published %} o {% else %} x {% endif%}
    <a class="bg-red-300" href="{% url 'articles:detail' article.id %}">
      {{ article.title }}
    </a>
  </h2>

  <p>
    {{ article.content|truncatewords:50 }}
  </p>
</article>
{% endfor %}

{% endblock %}

articles/templates/articles/new.html
{% extends "layouts/default.html" %}

{% block content %}
<h1 class="text-3xl">新增文章</h1>

<form action="{% url 'articles:index' %}"
      method="post"
      class="flex flex-col gap-4">

  {% csrf_token %}

  {% for field in form %}
    <div class="flex flex-col">
      {{ field.label_tag }}
      {{ field }}
    </div>
  {% endfor %}

  <div>
    <button class="btn btn-success">新增文章</button>
  </div>
</form>

{% endblock %}