articles/urls.py
from django.urls import path
from . import views
from comments import views as comment_views

app_name = "articles"

urlpatterns = [
    path("new/", views.new, name="new"),
    path("<int:id>/edit", views.edit, name="edit"),
    path("<int:id>/comments", comment_views.create, name="create_comment"),
    path("<int:id>/like", views.like, name="like"),
    path("<int:id>", views.detail, name="detail"),
    path("", views.index, name="index"),
]

pages/urls.py
from django.urls import path
from . import views
from articles.views import index

app_name = "pages"

urlpatterns = [
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("pricing/", views.pricing, name="pricing"),
    path("", index, name="home"),
    path("test/", views.test, name="test"),
]

sessions/urls.py
from django.urls import path
from . import views

app_name = "sessions"

urlpatterns = [
    path("new/", views.new, name="new"),
    path("", views.create, name="create"),
    path("logout/", views.logout, name="logout"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("new/", views.new, name="new"),
    path("", views.create, name="create"),
]

wretch/urls.py
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("", include("pages.urls")),
    path("articles/", include("articles.urls")),
    path("comments/", include("comments.urls")),
    path("users/", include("users.urls")),
    path("sessions/", include("sessions.urls")),
    path("payments/", include("payments.urls")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls()

templates/shared/message.html
{% comment %}
  保留 CSS 類別 alert-success alert-error alert-warning
{% endcomment %}
{% if messages %}
  {% for m in messages %}
    <template x-data="{show: true}" x-if="show">
      <div role="alert" class="flex justify-between alert alert-{{ m.tags }}">
        <span>{{ m }}</span>
        <button @click="show = false" class="btn btn-xs">x</button>
      </div>
    </template>
  {% endfor %}
{% endif %}

templates/shared/navbar.html
<nav id="navbar-main" class="bg-green-200 py-4 px-8 flex justify-between">
  <ul class="flex gap-4">
    <li><a href="{% url 'pages:home' %}">首頁</a></li>
    <li><a href="{% url 'pages:contact' %}">聯絡</a></li>
    <li><a href="{% url 'pages:about' %}">關於</a></li>
    <li><a href="{% url 'articles:index' %}">文章</a></li>
    <li><a href="{% url 'pages:pricing' %}">VIP</a></li>
  </ul>
  <ul class="flex gap-4">
    {% if user.is_authenticated %}
      <li>{{ user.username }}</li>
      <li><a href="#"
             hx-target="#navbar-main"
             hx-swap="outerHTML"
             hx-delete="{% url 'sessions:logout' %}">登出</a>
      </li>
    {% else %}
      <li><a href="{% url 'sessions:new' %}">登入</a></li>
      <li><a href="{% url 'users:new' %}">註冊</a></li>
    {% endif %}
  </ul>
</nav>